import 'package:flutter/widgets.dart';

bool isCantonese(BuildContext context) =>
    Localizations.localeOf(context).languageCode == 'zh';

String tr(BuildContext context, String english) =>
    isCantonese(context) ? (_cantonese[english] ?? english) : english;

const _cantonese = <String, String>{
  'Today': '今日',
  'All': '全部',
  'Library': '題庫',
  'Review': '溫習',
  'Settings': '設定',
  'Sync content': '同步內容',
  'Guest': '訪客',
  'Signed in': '已登入',
  'See all': '查看全部',
  'Make room for learning.': '留啲時間畀學習。',
  'Make room\nfor learning.': '留啲時間\n畀學習。',
  'Everything you can study, organised in one place.': '全部學習內容，一個地方搵晒。',
  'Search your study sets': '搜尋你嘅題組',
  'Most due': '最多待溫習',
  'Try another keyword or subject filter.': '試吓其他關鍵字或科目。',
  'Due items rise to the top. Missed answers stay easy to revisit.':
      '待溫習題目會排喺前面，錯題亦容易重溫。',
  'There are no review items due right now.': '而家冇題目要溫習。',
  'due today': '今日待溫習',
  'Start with recall, then check what really stuck.': '先試吓回想，再睇吓自己真正記得幾多。',
  'Start a practice test': '開始模擬測驗',
  'study sets': '學習題組',
  'Ready': '準備好',
  'for offline': '離線使用',
  'Nothing due right now.': '而家冇題目要溫習。',
  'Missed': '答錯',
  'Due now': '而家要溫習',
  'Due': '待溫習',
  'Practised': '已練習',
  'New': '新題目',
  'Multiple choice': '選擇題',
  'Flashcard': '字卡',
  'Close': '關閉',
  'End session': '結束練習',
  'Answer shown. Tap to flip back.': '已顯示答案，撳一下返回。',
  'Tap to reveal answer': '撳一下睇答案',
  'Tap the card to flip it back': '撳字卡返回',
  'Tap card to reveal the answer': '撳字卡睇答案',
  'Progress is saved on this device.': '進度已儲存在呢部裝置。',
  'Why': '解釋',
  'Correct answer': '正確答案',
  'Your answer': '你嘅答案',
  'correct': '答啱',
  'recalled': '記得',
  'Session complete': '練習完成',
  'got it': '識咗',
  'to revisit': '要重溫',
  'now practised': '已練習',
  'Search study sets': '搜尋學習題組',
  'Your study sets': '你嘅學習題組',
  'Open library': '開啟題庫',
  'Review, not relearn.': '溫習，唔使重頭學。',
  'No matching study sets': '搵唔到相符嘅題組',
  'You are caught up': '全部都溫習好喇',
  'Review set': '溫習題組',
  'Practise mistakes': '練習錯題',
  'Your learning space': '你嘅學習空間',
  'Account & progress': '帳戶同進度',
  'Guest mode. No account needed to study.': '訪客模式，學習唔使開帳戶。',
  'Guest and account progress stay separate. Acatrain never uploads guest progress automatically.':
      '訪客同帳戶嘅進度會分開儲存。Acatrain 唔會自動上傳訪客進度。',
  'Sign in or create account': '登入或建立帳戶',
  'Sync progress': '同步進度',
  'Sign out': '登出',
  'Live content': '最新內容',
  'Connected to your published content service.': '已連接已發佈嘅內容服務。',
  'Bundled demo. Cloud service is not configured.': '示範內容；未設定雲端服務。',
  'Check for content updates': '檢查內容更新',
  'Display & motion': '顯示同動畫',
  'Appearance': '外觀',
  'Language': '顯示語言',
  'Subscription': '訂閱',
  'View plans': '睇吓方案',
  'Plans': '方案',
  'Make it yours.': '整成你鍾意嘅樣。',
  'Each plan dresses Acatrain in a more luxurious theme.': '每個方案都會為 Acatrain 換上更華麗嘅主題。',
  'Demo checkout. You will never be charged.': '示範付款，永遠唔會真係收費。',
  'Demo only. Nothing was charged.': '只係示範，冇收任何費用。',
  'Simulated payment · not charged': '模擬付款 · 不會收費',
  'Back to the Evergreen theme.': '已轉返常青主題。',
  '/ month': '/ 月',
  'Current plan': '目前方案',
  'Switch to Free': '轉返免費版',
  'Monthly': '按月',
  'Yearly': '按年',
  '/ year': '/ 年',
  '2 months free with yearly': '按年付款送兩個月',
  'Change your plan': '轉換方案',
  'Most popular': '最受歡迎',
  'High-roller pick': '豪客之選',
  'Upgrade': '升級',
  'Downgrade': '降級',
  'Switch to yearly': '轉為按年',
  'Switch to monthly': '轉為按月',
  'Active': '生效中',
  'Cancelled': '已取消',
  'Access until': '可用至',
  'Next payment': '下次付款',
  'Payment method': '付款方式',
  'Billing': '收費週期',
  'Change plan': '轉換方案',
  'Resume subscription': '恢復訂閱',
  'Cancel subscription': '取消訂閱',
  'Keep plan': '保留方案',
  'Billing history': '付款紀錄',
  'Paid': '已付款',
  'Demo receipt. No money moved.': '示範收據，冇任何金錢轉移。',
  'Subscribe': '訂閱',
  'This device': '呢部裝置',
  'Pick a checkout to try. Every one is simulated.': '揀一個付款方式試吓，全部都係模擬。',
  'Evergreen': '常青',
  'Sapphire': '藍寶石',
  'Amethyst & Gold': '紫晶鎏金',
  'Noir & Gold': '黑金',
  'Evergreen theme': '常青主題',
  'Sapphire theme': '藍寶石主題',
  'Amethyst & Gold theme': '紫晶鎏金主題',
  'Noir & Gold theme': '黑金主題',
  'Every study set': '所有學習題組',
  'Offline progress': '離線進度',
  'Everything in Free': '包括免費版所有功能',
  'Everything in Starter': '包括 Starter 所有功能',
  'Everything in Pro': '包括 Pro 所有功能',
  'Supporter badge': '支持者徽章',
  'Gilded hero card': '鎏金主卡',
  '20x the flair': '20 倍氣派',
  'Personal info': '個人資料',
  'Name': '名稱',
  'Email': '電郵',
  'Save': '儲存',
  'Connect Google': '連結 Google',
  'Google connected': '已連結 Google',
  'Account actions': '帳戶操作',
  'Choose how Acatrain looks on this device.': '揀呢部裝置嘅外觀。',
  'System follows your device setting.': '跟隨系統會使用裝置嘅外觀設定。',
  'Choose the display language.': '揀選顯示語言。',
  'Study content keeps its original language.': '學習內容會保留原有語言。',
  'Animations follow the display refresh rate.': '動畫會跟隨螢幕更新率。',
  'The device can lower its refresh rate to save power.': '裝置可能會降低更新率以慳電。',
  'Motion follows your device settings.': '動畫跟隨裝置設定。',
  'System': '跟隨系統',
  'Light': '淺色',
  'Dark': '深色',
  'English': '英文',
  'Cantonese (繁體中文)': '廣東話（繁體中文）',
  'Start learning': '開始學習',
  'Practice test': '模擬測驗',
  'Flashcards': '字卡',
  'Review due': '溫習到期題目',
  'Mini games': '學習小遊戲',
  'Match pairs': '配對問答',
  'Quick answers': '快速答題',
  'Connect each question to its answer.': '將每條問題配返正確答案。',
  'Choose one card from each column. Missed pairs are ready to review.':
      '喺兩邊各揀一張卡。配錯嘅題目會加入溫習清單。',
  'Try another pair': '再試另一組配對',
  'Pick the answer that fits best.': '揀最合適嘅答案。',
  'Correct!': '答啱喇！',
  'Take a look at the highlighted answer.': '睇吓標示咗嘅正確答案。',
  'Game complete': '遊戲完成',
  'Play again': '再玩一次',
  'Inside this set': '題組內容',
  'Question': '問題',
  'Answer': '答案',
  'Again': '再試',
  'Got it': '識喇',
  'Show answer': '顯示答案',
  'Continue': '繼續',
  'Back to learning': '返回學習',
  'Review queue': '待溫習題目',
  'well-practised': '已熟習',
  'items offline': '離線題目',
  'Continue with Google': '使用 Google 繼續',
  'or use email': '或者使用電郵',
  'Password': '密碼',
  'Forgot password?': '忘記密碼？',
  'Welcome back': '歡迎返嚟',
  'We can send a one-time Firebase email link. On desktop/mobile you can paste the full link back here.':
      '我哋可以傳送一次性登入連結。你可以喺電腦或手機將連結貼返喺度。',
  'Your cloud account only exists to sync learning progress across devices.':
      '雲端帳戶用嚟喺裝置之間同步學習進度。',
  'or': '或者',
  'Offline ready. Your progress stays on this device.': '離線模式已準備好，進度會留喺呢部裝置。',
  'Signed in. Use Sync progress to merge this account across devices.':
      '已登入。使用「同步進度」合併唔同裝置嘅進度。',
  'Signed in with Google. Use Sync progress to merge progress across devices.':
      '已使用 Google 登入。使用「同步進度」合併進度。',
  'Google is connected to your account. Your progress stays with this account.':
      'Google 已連結到你嘅帳戶，進度會保留。',
  'Progress synced. Most recent review wins per item.': '進度已同步，每題以最近一次溫習為準。',
  'Personal info saved.': '個人資料已儲存。',
  'Signed out. Guest progress restored.': '已登出，已還原訪客進度。',
  'This email already has an account. Sign in with its password to connect Google.':
      '呢個電郵已有帳戶。請用密碼登入，再連結 Google。',
  'This email already has a password account. Sign in with your password, then connect Google in Personal info.':
      '呢個電郵已有密碼帳戶。請先用密碼登入，再到「個人資料」連結 Google。',
  'Enter a valid email address.': '請輸入有效電郵地址。',
  'That email address already has an account.': '呢個電郵地址已有帳戶。',
  'This Google account is already linked to another account.':
      '呢個 Google 帳戶已連結其他帳戶。',
  'The email or password is incorrect.': '電郵或密碼唔正確。',
  'Choose a stronger password with at least 6 characters.': '請設定最少 6 個字元嘅密碼。',
  'This sign-in method is not enabled in Firebase Authentication.':
      'Firebase Authentication 未啟用呢種登入方式。',
  'Too many attempts. Try again later.': '嘗試次數太多，請遲啲再試。',
  'That email link has expired. Request a new one.': '電郵連結已過期，請重新索取。',
  'That email link or code is invalid.': '電郵連結或驗證碼無效。',
  'Could not create the account.': '未能建立帳戶。',
  'Could not sign in with email and password.': '未能使用電郵同密碼登入。',
  'Could not connect this Google account.': '未能連結呢個 Google 帳戶。',
  'Could not sign in with Google.': '未能使用 Google 登入。',
  'Password reset email sent. Check your inbox.': '重設密碼電郵已傳送，請檢查收件匣。',
  'Choose a name between 1 and 80 characters.': '名稱長度要介乎 1 至 80 個字元。',
  'Could not save your name.': '未能儲存名稱。',
  'Google sign-in was canceled.': '已取消 Google 登入。',
  'Google sign-in could not be completed. Check the app OAuth configuration.':
      '未能完成 Google 登入，請檢查應用程式嘅 OAuth 設定。',
  'Create your account': '建立你嘅帳戶',
  'Sign in without a password': '免密碼登入',
  'Create account': '建立帳戶',
  'Sign in': '登入',
  'Connecting...': '連線中⋯',
  'Complete sign in': '完成登入',
  'Send sign-in link': '傳送登入連結',
  'Email link or oobCode': '電郵連結或 oobCode',
  'Use email and password': '使用電郵同密碼',
  'Use passwordless email link': '使用免密碼電郵連結',
  'Already have an account? Sign in': '已有帳戶？登入',
  'New to Acatrain? Create an account': '首次使用 Acatrain？建立帳戶',
};
